## üß≠ Data Loading ‚Äî USGS Global Earthquake Dataset (1900‚ÄìPresent)

This dataset contains detailed information on significant global earthquakes
(magnitude ‚â• 5.0) recorded since 1900. Sourced weekly from the United States
Geological Survey (USGS), it includes comprehensive data such as timestamp,
location (latitude & longitude), magnitude, depth, and measurement network details.

Earthquakes originate from tectonic activity across both highly seismic regions, such
as the Pacific Ring of Fire, and less active zones like Europe and Africa. The dataset
serves as a valuable resource for analyzing long-term seismic patterns, understanding
geological behavior, and developing predictive models.

### Key Columns Explained:
- **time**: Timestamp in milliseconds since Unix epoch (UTC) representing event occurrence.
- **latitude / longitude**: Coordinates of the earthquake's epicenter (in decimal degrees).
- **depth**: Depth of the event in kilometers.
- **mag**: Reported earthquake magnitude.
- **magType**: Type of magnitude measurement (e.g., mb, ml, mw).
- **nst**: Number of stations used to compute the earthquake solution.
- **gap**: Largest azimuthal gap between stations, in degrees.
- **dmin**: Distance to the nearest recording station (in degrees).
- **rms**: Root-mean-square residual of seismic station readings.
- **net / id**: Network and unique event identifiers.
- **updated**: Last update timestamp for the event record.
- **place**: Human-readable location description.
- **type**: Event type (e.g., ‚Äúearthquake‚Äù, ‚Äúexplosion‚Äù, ‚Äúquarry blast‚Äù).
- **horizontalError / depthError / magError**: Uncertainty measurements of calculations.
- **status**: Event status within USGS catalog (e.g., ‚Äúreviewed‚Äù, ‚Äúautomatic‚Äù).
- **locationSource / magSource**: Networks providing the location and magnitude data.

This dataset supports exploratory analyses, time-series pattern detection, and
predictive-modeling of seismic events worldwide, making it highly applicable to
earthquake research and risk assessment projects.

Source Link: https://www.kaggle.com/datasets/usamabuttar/significant-earthquakes?resource=download

In [ ]:
# Mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:

# Load USGS Earthquake Data
import pandas as pd

# Replace this path or URL with your actual dataset location
data_path = "/content/drive/MyDrive/ImpactSense_Oct25/data/earthquakes_data.csv"
earthquake_df = pd.read_csv(data_path)

# Display basic information and preview
earthquake_df.info()
earthquake_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110133 entries, 0 to 110132
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0       110133 non-null  int64
 1   time             110133 non-null  object
 2   latitude         110133 non-null  float64
 3   longitude        110133 non-null  float64
 4   depth            109848 non-null  float64
 5   mag              110133 non-null  float64
 6   magType          110133 non-null  object
 7   nst              39492 non-null   float64
 8   gap              49783 non-null   float64
 9   dmin             29839 non-null   float64
 10  rms              81386 non-null   float64
 11  net              110133 non-null  object
 12  id               110133 non-null  object
 13  updated          110133 non-null  object
 14  place            109242 non-null  object
 15  type             110133 non-null  object
 16  horizontalError  28459 non-null   float64
 17  depthError       60418 non-null   float64
 18  magError         43072 non-null   float64
 19  magNst           50108 non-null   float64
 20  status           110133 non-null  object
 21  locationSource   110133 non-null  object
 22  magSource        110133 non-null  object
dtypes: float64(12), int64(1), object(10)
memory usage: 19.3+ MB

,Unnamed: 0,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,0,1900-10-09T12:25:00.000Z,57.09,-153.48,NaN,7.86,mw,NaN,NaN,NaN,...,2022-05-09T14:44:17.838Z,"16 km SW of Old Harbor, Alaska",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,pt
1,1,1901-03-03T07:45:00.000Z,36.00,-120.50,NaN,6.40,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"12 km NNW of Parkfield, California",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,ell
2,2,1901-07-26T22:20:00.000Z,40.80,-115.70,NaN,5.00,fa,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"6 km SE of Elko, Nevada",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sjg
3,3,1901-12-30T22:34:00.000Z,52.00,-160.00,NaN,7.00,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,south of Alaska,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,abe
4,4,1902-01-01T05:20:30.000Z,52.38,-167.45,NaN,7.00,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"113 km ESE of Nikolski, Alaska",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,abe

## üîç Data Inspection ‚Äî Exploring Earthquake Dataset Structure

In this stage, we perform an initial inspection of the earthquake data
to understand its overall structure, completeness, and summary statistics.

Typical inspection steps include:
1. Viewing the dataset shape and column names.
2. Identifying data types and non-null counts.
3. Checking for missing values.
4. Reviewing unique entries in categorical columns.
5. Exploring basic descriptive statistics to detect scale variations or anomalies.

In [ ]:
# View the dataset shape (rows √ó columns)
print("Dataset shape:", earthquake_df.shape)

Dataset shape: (110133, 23)

In [ ]:
# Display the first few records
display(earthquake_df.head())

,Unnamed: 0,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,0,1900-10-09T12:25:00.000Z,57.09,-153.48,NaN,7.86,mw,NaN,NaN,NaN,...,2022-05-09T14:44:17.838Z,"16 km SW of Old Harbor, Alaska",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,pt
1,1,1901-03-03T07:45:00.000Z,36.00,-120.50,NaN,6.40,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"12 km NNW of Parkfield, California",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,ell
2,2,1901-07-26T22:20:00.000Z,40.80,-115.70,NaN,5.00,fa,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"6 km SE of Elko, Nevada",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,sjg
3,3,1901-12-30T22:34:00.000Z,52.00,-160.00,NaN,7.00,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,south of Alaska,earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,abe
4,4,1902-01-01T05:20:30.000Z,52.38,-167.45,NaN,7.00,ms,NaN,NaN,NaN,...,2018-06-04T20:43:44.000Z,"113 km ESE of Nikolski, Alaska",earthquake,NaN,NaN,NaN,NaN,reviewed,ushis,abe

In [ ]:
# Display column names and their data types
print("\n--- Column Details ---")
earthquake_df.info()

--- Column Details ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110133 entries, 0 to 110132
Data columns (total 23 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Unnamed: 0       110133 non-null  int64
 1   time             110133 non-null  object
 2   latitude         110133 non-null  float64
 3   longitude        110133 non-null  float64
 4   depth            109848 non-null  float64
 5   mag              110133 non-null  float64
 6   magType          110133 non-null  object
 7   nst              39492 non-null   float64
 8   gap              49783 non-null   float64
 9   dmin             29839 non-null   float64
 10  rms              81386 non-null   float64
 11  net              110133 non-null  object
 12  id               110133 non-null  object
 13  updated          110133 non-null  object
 14  place            109242 non-null  object
 15  type             110133 non-null  object
 16  horizontalError  28459 non-null   float64
 17  depthError       60418 non-null   float64
 18  magError         43072 non-null   float64
 19  magNst           50108 non-null   float64
 20  status           110133 non-null  object
 21  locationSource   110133 non-null  object
 22  magSource        110133 non-null  object
dtypes: float64(12), int64(1), object(10)
memory usage: 19.3+ MB

In [ ]:
# Check for missing values across all columns
print("\n--- Missing Values Summary ---")
missing_summary = earthquake_df.isnull().sum().sort_values(ascending=False)
display(missing_summary[missing_summary > 0])

--- Missing Values Summary ---

horizontalError    81674
dmin               80294
nst                70641
magError           67061
gap                60350
magNst             60025
depthError         49715
rms                28747
place                891
depth                285
dtype: int64

In [ ]:
# View unique event types and magnitude types
print("\n--- Unique Event Types ---")
print(earthquake_df["type"].unique())

--- Unique Event Types ---
['earthquake' 'nuclear explosion' 'explosion' 'rock burst' 'mine collapse'
 'volcanic eruption' 'landslide']

In [ ]:
print("\n--- Unique Magnitude Types ---")
print(earthquake_df["magType"].unique())

--- Unique Magnitude Types ---
['mw' 'ms' 'fa' 'ml' 'mint' 'mb' 'lg' 'uk' 'mh' 'mwc' 'md' 'mb_lg' 'mc'
 'ma' 'mwb' 'mww' 'mwr' 'mlg' 'm' 'Md' 'Ml' 'ms_20' 'mwp' 'Mi' 'Mb'
 'ml(texnet)']

In [ ]:
# Get statistical overview for numerical columns
print("\n--- Descriptive Statistics ---")
display(earthquake_df.describe())

--- Descriptive Statistics ---

,Unnamed: 0,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,110133.000000,110133.000000,110133.000000,109848.000000,110133.000000,39492.000000,49783.000000,29839.000000,81386.000000,28459.000000,60418.000000,43072.000000,50108.000000
mean,55066.000000,3.692374,41.402767,61.340488,5.441380,141.146283,65.583967,4.199523,0.947658,7.864240,7.282601,0.148807,64.465774
std,31792.802936,30.432835,121.960837,107.639693,0.479188,117.023302,39.212698,5.191667,0.365004,3.912147,10.139548,0.145688,101.396169
min,0.000000,-77.080000,-179.997000,-4.000000,5.000000,0.000000,6.500000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000
25%,27533.000000,-17.855000,-72.002000,10.000000,5.100000,63.000000,37.000000,1.296000,0.800000,6.200000,1.900000,0.055000,13.000000
50%,55066.000000,-0.696000,100.391000,33.000000,5.300000,103.000000,57.000000,2.514000,0.950000,7.750000,4.600000,0.081000,30.000000
75%,82599.000000,29.883500,143.175000,51.000000,5.630000,179.000000,84.400000,4.915000,1.100000,9.375000,8.200000,0.200000,68.000000
max,110132.000000,87.386000,180.000000,700.000000,9.500000,929.000000,360.000000,50.901000,69.320000,99.000000,1091.900000,1.840000,1144.000000

In [ ]:
# Checking for duplicate records using unique ID
duplicate_count = earthquake_df.duplicated(subset=['id']).sum()
print(f"\nDuplicate Records Based on 'id': {duplicate_count}")

Duplicate Records Based on 'id': 9143

- **Observations**

Dataset & structure

100‚Äì200 synthetic rows (depending on notebook). Columns: age, salary, department, years_experience / satisfaction, IsManager.
salary contained missing values (~10); median imputation applied.
Summary statistics & distributions

Salary: reasonable spread with some high/low outliers; median near mean after imputation.
Age and YearsExperience distributions are approximately uniform/normal depending on generator seed.
Department counts vary ‚Äî some departments have more samples (possible class imbalance).
Missing values & imputation

Salary nulls were filled with median ‚Äî simple and safe but may bias department‚Äëspecific salary distributions.
Recommendation: consider group-wise median (by department/education) or model-based imputation for production.
Outliers

Boxplots reveal outliers in salary (e.g., marketing / specific departments).
IQR filter removed a small fraction of rows. Review removed rows before permanent deletion.
Relationships & correlations

Correlations between numeric features (age, salary, satisfaction/experience) are low to moderate ‚Äî no strong linear dependency found.
Scatterplots show weak positive relationship between experience and salary; managers cluster at higher salaries.
Department vs managerial status

Boxplots + stripplots show managers generally have higher median salaries than non‚Äëmanagers within departments.
Degree of difference varies by department; some departments have insufficient manager samples to compare reliably.
Visual checks

Histograms, heatmap, pairplot are useful for distribution and pairwise interaction checks.
Stacked bar / crosstabs show education composition by department ‚Äî helpful for group imputation/stratification.